name: Deploy to ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Rsync code to ECS (skip heavy folders)
        run: |
          rsync -az --delete \
            --exclude '.git' \
            --exclude 'node_modules' \
            --exclude '.next' \
            -e "ssh -p ${{ secrets.ECS_PORT }} -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.ECS_USER }}@${{ secrets.ECS_HOST }}:${{ secrets.ECS_PATH }}/

      - name: Install deps + build + restart pm2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USER }}
          port: ${{ secrets.ECS_PORT }}
          script: |
            set -e
            export PATH=$PATH:/usr/local/bin:/usr/bin
            mkdir -p "${{ secrets.ECS_PATH }}"
            cd "${{ secrets.ECS_PATH }}"
            echo "PWD=$(pwd)"
            echo "node=$(node -v || true)  npm=$(npm -v || true)  pm2=$(pm2 -v || true)"
            npm install --registry=https://registry.npmmirror.com
            npm run build
            if pm2 describe law-enforcement >/dev/null 2>&1; then
              pm2 restart law-enforcement
            else
              pm2 start npm --name law-enforcement -- start
            fi
            pm2 save